import { Inter } from "next/font/google";
import "./globals.css";
<%_ if (oauth2) { _%>
  import PrivateRoute from './config/auth/privateRoute';
<%_ } _%>

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
